strace-log-merge: enhance pid formatting
* strace-log-merge (max_suffix_length): New variable.
(iterate_logfiles, process_suffix, process_logfile): New functions.
Use them to choose the optimum width for pid column.
* NEWS: Mention this enhancement.
* tests/strace-log-merge-suffix.test: New test.
* tests/Makefile.am (MISC_TESTS): Add it.

diff --git a/strace-log-merge b/strace-log-merge
--- a/strace-log-merge
+++ b/strace-log-merge
@@ -33,18 +33,53 @@ fi
 
 logfile=$1
 
-for file in "$logfile".*; do
-	[ -f "$file" ] || continue
-	suffix=${file#"$logfile".}
-	[ "$suffix" -gt 0 ] 2> /dev/null ||
-		continue
-	pid=$(printf "%-5s" $suffix)
+iterate_logfiles()
+{
+	local file suffix
+
+	for file in "$logfile".*; do
+		[ -f "$file" ] || continue
+		suffix=${file#"$logfile".}
+		[ "$suffix" -gt 0 ] 2> /dev/null ||
+			continue
+		"$@" "$suffix" "$file"
+	done
+}
+
+max_suffix_length=0
+process_suffix()
+{
+	local suffix len
+	suffix="$1"; shift
+
+	len=${#suffix}
+	if [ $len -gt $max_suffix_length ]; then
+		max_suffix_length=$len
+	fi
+}
+
+process_logfile()
+{
+	local suffix file pid
+	suffix="$1"; shift
+	file="$1"; shift
+
+	pid=$(printf "%-*s" $max_suffix_length $suffix)
 	# Some strace logs have last line which is not '\n' terminated,
 	# so add extra newline to every file.
-	# grep -v '^$' removes empty lines which may result.
+	# Empty lines are removed later.
 	sed -n "s/^\($dd:\)\?\($dd:\)\?\($ds\.\)\?$ds /\2\4\6\7 $pid \0/p" < "$file"
 	echo
-done |
+}
+
+iterate_logfiles process_suffix
+
+[ $max_suffix_length -gt 0 ] || {
+	echo >&2 "${0##*/}: $logfile: strace output not found"
+	exit 1
+}
+
+iterate_logfiles process_logfile |
 	sort -s -n -k1,1 |
 	sed -n 's/^[0-9][0-9]* //p' |
 	grep -v '^$'
